#!/bin/sh
# Rebuild the stage-0 payload from the current src/ and update the local
# `stage-0` branch. Run this after landing changes to the compiler / codegen
# (e.g. once the `?`-in-def-names fix lands) so the checked-in bootstrap
# tracks src/ again.
#
# Does NOT push. It prints the push command at the end.
#
# One fresh `node` process per file (process-global gensym counter).
set -eu

REPO=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO"

BOOTSTRAP_REF=${BOOTSTRAP_REF:-stage-0}
MODULES="runtime sequence string ast reader expander analyzer compiler repl wisp
engine/node engine/browser
backend/escodegen/generator backend/escodegen/writer backend/javascript/writer"

command -v node >/dev/null || { echo "node not found" >&2; exit 1; }
git rev-parse --verify --quiet "$BOOTSTRAP_REF^{commit}" >/dev/null || {
  echo "branch '$BOOTSTRAP_REF' not found; fetch it first" >&2; exit 1; }

PAYLOAD=$(mktemp -d)
PREV=$(mktemp -d)
trap 'rm -rf "$PAYLOAD" "$PREV"' EXIT

# carry the static files (entry + package.json) forward from the current branch
git archive "$BOOTSTRAP_REF" | tar -x -C "$PREV"

echo "compiling src/*.wisp with the repo's own compiler..."
for m in $MODULES; do
  mkdir -p "$PAYLOAD/$(dirname "$m")"
  node -e 'var c=require("./compiler"),fs=require("fs");var o=c.compile(fs.readFileSync(process.argv[1],"utf8"),{"source-uri":process.argv[2]});if(o.error)throw o.error;process.stdout.write(o.code)' \
    "src/$m.wisp" "wisp/$m.wisp" > "$PAYLOAD/$m.js"
done
mkdir -p "$PAYLOAD/bin"
cp bin/wisp.js "$PAYLOAD/bin/wisp.js"
cp "$PREV/wisp-bootstrap.js" "$PAYLOAD/wisp-bootstrap.js"
cp "$PREV/package.json" "$PAYLOAD/package.json"

if diff -r "$PREV" "$PAYLOAD" >/dev/null 2>&1; then
  echo "stage-0 already matches src/ - nothing to do."
  exit 0
fi

WT=$(mktemp -d)
TMPBRANCH="stage-0-refresh-$$"
git worktree add --orphan -b "$TMPBRANCH" "$WT" >/dev/null
tar -C "$PAYLOAD" -cf - . | tar -C "$WT" -xf -
MASTER_SHA=$(git rev-parse --short HEAD)
( cd "$WT"
  git add -A
  git add -f bin/wisp.js
  git commit -q -m "stage-0: rebuild from $MASTER_SHA

Self-hosted output of src/*.wisp, one fresh compiler process per file,
--source-uri threaded. Regenerated by scripts/refresh-stage-0.sh.
Do not edit by hand." )
git branch -f "$BOOTSTRAP_REF" "$TMPBRANCH"
git worktree remove "$WT"
git branch -D "$TMPBRANCH" >/dev/null
git worktree prune

echo
echo "local '$BOOTSTRAP_REF' updated to $(git rev-parse --short "$BOOTSTRAP_REF")."
echo "review it, then:  git push origin $BOOTSTRAP_REF"
echo "refresh the local working copy with:  make bootstrap-clean && make"
